name: Clone Private Repo

on:
  push:
  pull_request:

jobs:
  clone-private-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Get private repo URL and token from environment variables
        env:
          PRIVATE_REPO_URL: ${{ secrets.PRIVATE_REPO_URL }}
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Private repo URL: $PRIVATE_REPO_URL"

      - name: Clone private repo
        run: |
          git clone $PRIVATE_REPO_URL .
          git checkout $GITHUB_SHA  # Checkout the commit associated with the event

      - name: Verify cloned repo
        run: |
          ls -al
          git remote -v
